### ISSUE TITLE
need a concept to handle Configurable Features that depend on third-party libraries

### ISSUE THREAD

**Issue by ntruchsess** [firmata/arduino#132]
Current Configurable-features all use libraries that either come with the Arduino-IDE or include their own or forked version in directory 'utility'. Not including such library into firmata utility or installing it into the Arduino library-directory would result in compile-errors even when the feature being dependent on this lib would not be enabled in ConfigurableFirmata.ino as the Arduino-ide just tries to compile everything in utility-directory.

This problem arises with #131 which depends on RCSwitch-library. We need a new way to enable/disable Configurable-features that omits compilation of Features that are not enabled. A possible solution would to move the configuration of features to a separate header-file that is included both by ConfigurableFirmata.ino and all feature-classes.

Any other thoughts?

**Comment by soundanalogous** [comment]
This issue was moved to firmata/ConfigurableFirmata#1
