### ISSUE TITLE
add comment in StandardFirmata about using Serial1

### ISSUE THREAD

**Issue by soundanalogous** [firmata/arduino#160]
Add a comment to the setup function in StandardFirmata to describe how to use Serial1 or other Stream implementations with Firmata.

Also add a comment about adding `while (!Serial);` when using an Arduino Leonardo or Micro.

**Comment by q2dg** [comment]
Come on guys! This can be done in 1 minute!

**Comment by soundanalogous** [comment]
You care to submit a pull request then @q2dg? I don't have much time to work on this project and contributions are rare but always welcome. I've you're interested, start with the protocol description: https://github.com/firmata/protocol/pull/28.

**Comment by soundanalogous** [comment]
added in this commit: https://github.com/firmata/arduino/commit/2bc2893f11aec15a8901716d9ce4de27c3fc064d
