### ISSUE TITLE
NewPing, Firmata & Maxuino

### ISSUE THREAD

**Issue by sparrowhands** [firmata/arduino#164]
Hi all,

I am using the NewPing library (http://playground.arduino.cc/Code/NewPing) with the 4-pin Ultrasonic HC-SR04. I wish to read the distance (serial) data into Maxuino using Firmata. Is there a simple way to integrate the NewPing code into the StandardFirmata sketch and hence read the values in Maxuino?

I am a Max programmer with no C-experience.

Any thoughts would be much appreciated,

Thanks,

Michael

**Comment by soundanalogous** [comment]
Wrapping a library such as NewPing is now possible through the new ConfigurableFirmata architecture: https://github.com/firmata/ConfigurableFirmata#firmata-wrapper-libraries
