### ISSUE TITLE
Arduino hangs and serial doesn't respond

### ISSUE THREAD

**Issue by zanechua** [firmata/arduino#177]
The original post is below which was posted on Arduino Stack Exchange, they said that the culprit was most likely firmata, is this the case? If so, How do I go about debugging the issue here.

http://arduino.stackexchange.com/questions/6666/raspberry-pi-with-arduino-serial-connection-stops-working

This is the hardware set-up at home, 

Raspberry Pi GPIO -> Logic Level Converter -> Arduino -> Multiple Relays

![enter image description here][1]

I am running Raspbian and NodeJS on the Pi while the Arduino is loaded with StandardFirmata.
I connect NodeJS to the Arduino with the johnny-five package and it works well after it's started. But after extended periods, a few hours? The Arduino stops responding. Whatever command that I send to the Arduino won't be acted on. It's as though as the Arduino hung.
Both the Raspberry Pi and Arduino are being powered indenpendently with a 1A Nokia USB Adapter.

1. johnny-five : https://github.com/rwaldron/johnny-five\
2. StandardFirmata: github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino
3. NodeJS Server Code: gist.github.com/zanechua/f52a3d72946d7214f7cc

  [1]: http://i.stack.imgur.com/J8Ja4.png

**Comment by zanechua** [comment]
I've just managed to find the time to change it to the Leonardo Board.

I'm leaving it on, It's using the latest Firmata 2.4.1. We'll see how it goes.

**Comment by zanechua** [comment]
Okay. The Leonardo seems to be perfectly fine even after 4 days or so.. So i guess it's my Uno?

**Comment by soundanalogous** [comment]
I think your latest test has established this issue has nothing to do with Firmata. Perhaps there is an issue with your Uno. You may want to try with another Uno and if the problem still persists post it to the Arduino forum and provide a report of your findings along with code and a description of the hardware necessary to reproduce.

**Comment by zanechua** [comment]
@soundanalogous yup. I'll look at getting another Uno board and see if there's any difference there.
