### ISSUE TITLE
compile firmata and upload from command line

### ISSUE THREAD

**Issue by legrostdg** [firmata/arduino#183]
Is there a way to compile StandardFirmata.ino and to upload it to a board without using the IDE?

I tried to use [Arduino-Makefile](https://github.com/sudar/Arduino-Makefile) but I got https://github.com/sudar/Arduino-Makefile/issues/117

**Comment by soundanalogous** [comment]
There used to be but I removed the makefiles a while back since no one was keeping them up to date. Try this: https://github.com/firmata/arduino/blob/e2ae488888a005fbaec1ff302efce7140a8f3ba2/examples/StandardFirmata/Makefile. If it works I can add it back.

**Comment by ajfisher** [comment]
I use ino for this pretty much all the time. Involves a little bit of
symlinking things to the right place but vim + ino is a great dev combo.

**Comment by soundanalogous** [comment]
@ajfisher do you need the makefile to use ino or does it generate its own?

**Comment by ajfisher** [comment]
It does it's own though you can give it one to do things like set device
ports, arduino types etc.

**Comment by soundanalogous** [comment]
I'll leave this open in case anyone wants to contribute via creating documentation of how to do this and/or contributing any configs, makefiles, etc to make this happen.

**Comment by ajfisher** [comment]
I'll put some notes together around this as I've now got rid of using INO due to the project going stale. 

With Interchange I've moved across to using the Arduino CLI tool and it works very well. Will put some documentation together relating to that process for those who are looking to do this CLI only.

**Comment by soundanalogous** [comment]
Since this issue is not specific to Firmata and is really a broader issue about compiling and uploading sketches via the command line, I'm closing this issue.

**Comment by carrete** [comment]
I understand this is a very old issue, but this did show-up in my search for an answer to the same question. With [arduino-cli](https://arduino.github.io/arduino-cli/0.35/), these steps worked for me:

    arduino-cli lib install firmata servo
    arduino-cli compile -b arduino:avr:uno .
    arduino-cli upload -b arduino:avr:uno -p /dev/ttyACM0 .
    
This was with a sketch that I had previously created in the IDE.
