### ISSUE TITLE
create a wiki page documenting the Firmata library

### ISSUE THREAD

**Issue by soundanalogous** [firmata/arduino#188]
Like this but up to date: http://arduino.cc/en/reference/firmata.

Then either point the Arduino reference to the wiki here or update the ref on the Arduino site as well. It will be easier to keep up-to-date here.

**Comment by q2dg** [comment]
+1!

**Comment by q2dg** [comment]
I think this issue should be prioritary

**Comment by soundanalogous** [comment]
Firmata now uses Doxygen: https://github.com/firmata/arduino/tree/master/docs
