### ISSUE TITLE
Add chipKit Uno32 pin definition to Boards.h

### ISSUE THREAD

**Issue by rwaldron** [firmata/arduino#209]
These were used on Nodebots Day at the HeatSync Labs event: http://chipkit.net/wpcproduct/chipkit-uno32/

**Comment by soundanalogous** [comment]
There is a PR open for this: https://github.com/firmata/arduino/pull/154.  Need to follow up with the author regarding the state of that PR.

**Comment by rwaldron** [comment]
I probably should've looked first, sorry about that :|

**Comment by soundanalogous** [comment]
np it's a good reminder actually :)

**Comment by soundanalogous** [comment]
done
