### ISSUE TITLE
lower the minimal sampling interval

### ISSUE THREAD

**Issue by soundanalogous** [firmata/arduino#212]
The current minimal sampling interval of 10ms was set back when Arduino boards still used the ATMega168. The newer SAM architecture boards can likely handle a lower sampling interval. Determine a new minimal value.

**Comment by soundanalogous** [comment]
Also, for Firmata 3.0, consider the ability to set a sampling interval per feature.

**Comment by rwaldron** [comment]
Nice!

**Comment by soundanalogous** [comment]
done
