### ISSUE TITLE
Add Arduino pluggable usb midi to ConfigurableFirmata 

### ISSUE THREAD

**Issue by EchoEOL** [firmata/arduino#243]
Will there be support for Arduino 1.6.6 pluggable usb midi for ConfigurableFirmata

**Comment by soundanalogous** [comment]
How do you imagine using this feature?

**Comment by soundanalogous** [comment]
also, this issue should ideally be opened for [firmata/protocol](https://github.com/firmata/protocol) or [firmata/ConfigurableFirmata](https://github.com/firmata/ConfigurableFirmata) instead of here.
