### ISSUE TITLE
Prepend all defines with "FIRMATA_"

### ISSUE THREAD

**Issue by soundanalogous** [firmata/arduino#253]
New boards keep breaking Firmata (and likely other libraries) by including defines and macros with the same name in their libraries. Time to fix this once and for all and prepend "FIRMATA_" to all defines. This will break many sketches unfortunately (for example if people maintain their own version of StandardFirmata or something similar and upgrade to the version of the Firmata that changes the definitions). Probably best for 3.0 with incremental patches along the way.

**Comment by soundanalogous** [comment]
Another approach would be to switch to namespaced enums for Firmata 3.0

**Comment by DomAmato** [comment]
Namespaced enums is probably a safer route though for consistency prepending everything with FIRMATA_ would be easier and less confusing unless there was a strong naming convention for the namespacing

**Comment by soundanalogous** [comment]
No longer necessary since we now have namespacing.
