### ISSUE TITLE
ANY FIX FOR StandardFirmataBLE :i want to use it for Bluetooth HS 05, StandardFirmata is working fine.

### ISSUE THREAD

**Issue by saleemkhan0044** [firmata/arduino#298]
Arduino: 1.6.10 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Program Files (x86)\Arduino\libraries\Firmata\examples\StandardFirmataBLE\StandardFirmataBLE.ino: In function 'void setup()':

StandardFirmataBLE:764: error: 'stream' was not declared in this scope

   stream.setLocalName(FIRMATA_BLE_LOCAL_NAME);

   ^

C:\Program Files (x86)\Arduino\libraries\Firmata\examples\StandardFirmataBLE\StandardFirmataBLE.ino: In function 'void loop()':

StandardFirmataBLE:794: error: 'stream' was not declared in this scope

   if (!stream.poll()) return;

        ^

exit status 1
'stream' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by soundanalogous** [comment]
To use an HS-05, use StandardFirmata, not StandardFirmataBLE

StandardFirmataBLE is only for the Bluetooth Low Energy (BLE) boards such as the Arduino 101 Board and some RedBearLabs boards. It does not work with BT to Serial adapters, that is different Bluetooth technology not related to BLE.
