### ISSUE TITLE
Arduino resets the previous state

### ISSUE THREAD

**Issue by aliassad** [firmata/arduino#299]
when i send digital  message to arduino setdititalpin 8 high its work but when i send setdititalpin 9 high
the pin 8 goes low.
The arduino resets its self before sending a new message.

**Comment by soundanalogous** [comment]
Are you using any particular firmata client library or are you just sending data over a uart?

**Comment by soundanalogous** [comment]
Also, please paste in the exact message you are sending.

**Comment by aliassad** [comment]
device.getPin(8).sevalue(1);
device.getPin(9).sevalue(1);


//the pin 9 gets high only

Im using java client liberary firmata4j

**Comment by soundanalogous** [comment]
Are you setting the pin mode to OUTPUT for pins 8 and 9 before setting their value?

**Comment by rwaldron** [comment]
What client library/platform is being used?

**Comment by soundanalogous** [comment]
firmata4j (a Java client)

**Comment by aliassad** [comment]
yes I'm setting the pins mode as output before setting their value.

**Comment by soundanalogous** [comment]
I'm pretty sure the error is in the firmata4j library. There is nothing in StandardFirmata that would exhibit this behavior. I also did a quick test with the nodejs firmata.js library and this works as expected (the LEDs attached to pins 8 and 9 both light up):

```javascript
var Board = require("firmata");

Board.requestPort(function(error, port) {
  if (error) {
    console.log(error);
    return;
  }
  var board = new Board(port.comName);

  board.on("ready", function() {
    console.log("ready");
    board.pinMode(8, board.MODES.OUTPUT);
    board.pinMode(9, board.MODES.OUTPUT);

    board.digitalWrite(8, 1);
    board.digitalWrite(9, 1);
  });
});
```

**Comment by soundanalogous** [comment]
issue is in firmata4j for sure: https://github.com/kurbatov/firmata4j/issues/12#issuecomment-240325691
