### ISSUE TITLE
run javascript on arduino

### ISSUE THREAD

**Issue by yilunyu** [firmata/arduino#300]
Hey there,

I have a general question about using firmata. If I write a javascript program that tells my Arduino to indefinitely blink an LED, would it not work after I execute the program and disconnect the cable to my Arduino? Is there a way to run Javascript on the microcontroller itself?

**Comment by monteslu** [comment]
HI @yilunyu 

Most Arduinos dont have enough resources to run javascript directly.  If you need to run javascript directly on a device, you might want to consider something like the tessel2 or raspberry pi or nexthingco C.H.I.P
