### ISSUE TITLE
Imagitronics (Firmata.NET) link is dead

### ISSUE THREAD

**Issue by wbadry** [firmata/arduino#316]
Hi,
I tried to reach [Firmata.NET](http://www.imagitronics.org/projects/firmatanet) location  but I guess the whole project is now down.

![](https://s17.postimg.org/k6zqsrr5b/2016_11_03_17_45_37.png "Link is down")

Also I suggest you add [FirmataVB](http://www.acraigie.com/programming/firmatavb/firmatavb.html) by **Andrew Craigie** to .NET list

**Comment by soundanalogous** [comment]
Please submit a PR to add/update the links

**Comment by wbadry** [comment]
I did. Thanks for point out  👍
