### ISSUE TITLE
Support NodeMCU with StandardFirmata

### ISSUE THREAD

**Issue by wbadry** [firmata/arduino#338]
Hi,
I tried StandardFirmataWiFi with my [NodeMCU V3](http://www.c-sharpcorner.com/article/blinking-led-by-esp-12e-nodemcu-v3-module-using-arduinoide/) . It runs very well and I could've read/write DIO from C# application and also using [Arduino Remte Wiring API](https://github.com/ms-iot/remote-wiring).

The problem is StandardFirmata doesn't work on any of them. I tried [other clients](http://www.instructables.com/id/Arduino-Installing-Standard-Firmata/step6/Testing-Standard-Firmata/) which worked well on Arduino Uno but not NodeMCU. I paid attention to **BaudRate** but still not working.

Is there any plan to add support to NodeMCU with StandardFirmata ? Thanks

**Comment by soundanalogous** [comment]
StandardFirmataWiFi is StandardFirmata with a Wi-Fi transport rather than a Serial transport. Do you mean you'd like to just use NodeMCU over Serial rather than over Wi-Fi?

**Comment by wbadry** [comment]
Yes, you are correct. I don't understand if the difference between **StandardFirmata** and **StandardFirmataWiFi** is a metter of transport layer, how come serial is not running on Standard sketch?

**Comment by soundanalogous** [comment]
I figured users would only want to use ESP8266 boards over a Wi-Fi transport.

**Comment by wbadry** [comment]
You are correct again. But using StandardFirmata would allow many to use it with other clients supporting serial. If it is possible to add it to your feature list, I would appreciate it. Thanks in advance

**Comment by soundanalogous** [comment]
Okay, I see now what you are asking for. You are looking for compatibility with more clients and most clients currently only support Serial.

Technically an ESP8266 should work with StandardFirmata but may need to use `Serial1` instead of `Serial` and a baud rate other than 57600.

**Comment by soundanalogous** [comment]
Actually I don't see any reason why the NodeMCU would not work with StandardFirmata as long as you change the baud rate from 57600 to 9600. When used with StandardFirmataWi-Fi, if Serial debugging is enabled, I know ESP8266 boards do in fact print debug info to the console.

**Comment by wbadry** [comment]
Thanks 👍

**Comment by soundanalogous** [comment]
Also just so you know, using NodeMCU with StandardFirmata isn't going to access any special NodeMCU features. It will be just like using an Arduino Uno or other board.

**Comment by soundanalogous** [comment]
I figured out how to get it to work, but I'm not going to support a one-off build of StandardFirmata just for this. Follow these steps:

1. Make a copy of StandardFirmata and rename it to StandardFirmataESP
2. Insert this line: `if (i == 1 || i == 3) continue;` just after [this line](https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L724).

Pins 1 and 3 are the TX and RX pins so they have to be ignored or they will cause conflicts when using the USB serial connection.

The updated for loop should look like this:

```c++
  for (byte i = 0; i < TOTAL_PINS; i++) {
    // need to ignore pins 1 and 3 when using an ESP8266 board
    if (i == 1 || i == 3) continue;
    // pins with analog capability default to analog input
    // otherwise, pins default to digital output
    if (IS_PIN_ANALOG(i)) {
      // turns off pullup, configures everything
      setPinModeCallback(i, PIN_MODE_ANALOG);
    } else if (IS_PIN_DIGITAL(i)) {
      // sets the output to 0, configures portConfigInputs
      setPinModeCallback(i, OUTPUT);
    }

    servoPinMap[i] = 255;
  }
```

**Comment by wbadry** [comment]
@soundanalogous Thanks 😄 . It is up and running 👍 

![NodeMCU with StandaradFirmata](https://media.giphy.com/media/26gJzF2BC25pIybVS/source.gif
