### ISSUE TITLE
Problem connecting ESP8266 (wemos D1 by serial)

### ISSUE THREAD

**Issue by olmerg** [firmata/arduino#351]
Hi,
I 'am trying to connect the wemos D1 mini to [snap4arduino](http://snap4arduino.org/), but it only support serial, so I try to connect without success.
Today, I solve the problem, changing the standardFirmdataWifi to Serial Stream and  adding  ignore pins the two pins of the serial port.

```
#if defined(ESP8266_WIFI)
#define IS_IGNORE_PIN(p)  ((p) == 1 || (p) == 3)
```

I do not how to integrate this in the code of the library to work by default.

Thanks

**Comment by soundanalogous** [comment]
What I've been trying to avoid, but will ultimately have to do at some point is adding a config.h file to  StandardFirmata and StandardFirmataPlus.

**Comment by soundanalogous** [comment]
In the mean time, add the following to StandardFirmata.ino or StandardFirmataPlus.ino (whichever you typically use) just above `Firmata.begin(57600);`

```c++
#ifdef ESP8266
  Firmata.setPinMode(1, PIN_MODE_IGNORE);
  Firmata.setPinMode(3, PIN_MODE_IGNORE);
#endif
```

There is no need to modify StandardFirmataWiFi to accomplish this.

**Comment by olmerg** [comment]
Nice, thanks by your soon support.
Yes, after I understood the code I view that is not necessary to work with  StandardFirmataWiFi.

May be a config.h is not a bad idea if there is possible to add new sensors like ultrasound or LCD, just and idea, taking the functions like [firmmata collection](https://github.com/mdcanham/Snap4Arduino-Firmata)

**Comment by soundanalogous** [comment]
@olmerg you should look at [ConfigurableFirmata](https://github.com/firmata/ConfigurableFirmata) which is a module-based approach to Firmata firmware.

**Comment by Timopheym** [comment]
Hi! @olmerg, i am trying to connect NodeMCUv3 based on ESP-12E to Snap4Arduino, and it does freely connect j5, BUT on "Connect Arduino"  
And it prints "Could not talk to arduino in port /dev/ttyUSB0" 
![image](https://cloud.githubusercontent.com/assets/525039/23535521/d5a22e38-ffcf-11e6-85e3-7d596ffece18.png)
I did tried your change 
```
#if defined(ESP8266_WIFI)
#define IS_IGNORE_PIN(p)  ((p) == 1 || (p) == 3)
```
With StandartFirmataWIFI but it didn't help. 

What am i doing wrong?

Thanks!

Here is it's pins: 
![](https://s-media-cache-ak0.pinimg.com/originals/47/be/9d/47be9d326bb367466f3c27e9f9577c04.jpg)

**Comment by soundanalogous** [comment]
Use this sketch: https://gist.github.com/soundanalogous/87ea10c07c3f072cb46d8cad206b42d1

**Comment by olmerg** [comment]
Thank you.

**Comment by amindadgar** [comment]
> Use this sketch: https://gist.github.com/soundanalogous/87ea10c07c3f072cb46d8cad206b42d1

Thanks for your support soundanalogous. I tried your code and a code from another person I've attached below, but I still have no success. My board is Arduino Wemos D1 R1 and the board I'm trying to connect it is raspberry pie and the software is node-red.

 
https://github.com/kotl/esp8266-firmata/blob/master/examples/ESP8266FirmataWifi/ESP8266FirmataWifi.ino

**Comment by amindadgar** [comment]
> In the mean time, add the following to StandardFirmata.ino or StandardFirmataPlus.ino (whichever you typically use) just above `Firmata.begin(57600);`
> 
> ```c++
> #ifdef ESP8266
>   Firmata.setPinMode(1, PIN_MODE_IGNORE);
>   Firmata.setPinMode(3, PIN_MODE_IGNORE);
> #endif
> ```
> 
> There is no need to modify StandardFirmataWiFi to accomplish this.

After Adding the codes you gave to StandardFirmataPlus.ino ( Or StandardFirmata.ino), I got this error below shown in the picture

![image](https://user-images.githubusercontent.com/48308230/118778917-d0f59b80-b89f-11eb-87f1-6c8295b454c4.png)

Any help would be really appreciated!

**Comment by soundanalogous** [comment]
All of those issues are coming from node-red, not Firmata.
