### ISSUE TITLE
[v3.0.0] Firmware callback should provide pointer to the string

### ISSUE THREAD

**Issue by zfields** [firmata/arduino#354]
I should have given it its own callback type to start with. v2.5.5 has only been out for a few days, could maybe fudge and fix it real fast if it's okay with @soundanalogous.

**Comment by soundanalogous** [comment]
It's okay to push to master, but I'm not sure I'm going cut another bugfix release right away unless v2.5.5 is broken because of this.

**Comment by zfields** [comment]
It will not break the FirmataClass API.

**Comment by zfields** [comment]
This is can be closed. We were able to make this update without breaking backward compatibility.
