### ISSUE TITLE
Firmata strings encoded incorrectly

### ISSUE THREAD

**Issue by zfields** [firmata/arduino#363]
This needs a patch rev [v2.5.6]. I encoded Firmata strings directly (not as two bytes), including the Firmware name, but I couldn't detect it because it is ASCII (7-bits), and I had parsed the firmware name incorrectly.

I was refactoring the parser's firmware string decoder to use your logic for strings, when I realized what I had done.

I have the pull request ready to patch...

**Comment by zfields** [comment]
I discovered it on the ESP8266, because your node client parses the firmware name. I didn't see it before, because the analog data scrolls so fast and I never scrolled back up to the top.

**Comment by soundanalogous** [comment]
I2C also appears to be broken in 2.5.5

**Comment by soundanalogous** [comment]
Your latest update fixes the I2C issue as well. Looks like in 2.5.5 all sysex data was being parsed as strings.
