### ISSUE TITLE
StandardFirmataWiFi Problem: Client disconnects every 20 seconds

### ISSUE THREAD

**Issue by Treppenhouse** [firmata/arduino#376]
Hello,
I am running the _StandardFirmataWiFi_ example on my **Arduino MEGA 2560** with the **Wifi Shield**. 

I set the configuration parameter from my WiFi network in the _wifiConfig.h_ and have the sketch run on the arduino. Initially, the connection establishes successfully. However, shortly after, the connection is disconnected. Every 20 seconds or so the connection establishes before disconnecting again. See the output of the serial monitor below:
```
StandardFirmataWiFi will attempt a WiFi connection using the legacy WiFi library.
Using static IP: 192.168.178.32
Attempting to connect to WPA SSID: ChaosWG
WiFi setup done
SSID: ChaosWG
IP Address: 192.168.178.32
signal strength (RSSI): -75 dBm
TCP connection established
TCP connection disconnected
TCP connection established
TCP connection disconnected
TCP connection established
```
Do you have any idea why this happens or how the cause of this can be found? 

Thanks in advance for any answers!

**Comment by soundanalogous** [comment]
Could be an issue with the old Wi-Fi shield library. Try forcing the `maintain()` method to return `true` in [WiFiServerStream](https://github.com/firmata/arduino/blob/master/utility/WiFiServerStream.h#L72) or [WiFiClientStream](https://github.com/firmata/arduino/blob/master/utility/WiFiClientStream.h#L81) (depending on if you have the firmware configured as a TCP server or client). Then determine if the connection is maintained. If that works, this is not the right fix, but it would indicate something isn't right in the connection state logic.
