### ISSUE TITLE
I2C protocol lists delay in microseconds as optional, but StandardFirmata.ino grabs bytes from buffer either way

### ISSUE THREAD

**Issue by zfields** [firmata/arduino#382]
I2C Protocol:
https://github.com/firmata/protocol/blob/master/i2c.md#i2c-config

StandardFirmata.ino:
https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L587

We need to check for `argc` to ensure we were sent a value. Currently, the i2c implementation will take any bytes sitting in the sysex buffer.

**Comment by soundanalogous** [comment]
Good catch!

**Comment by zfields** [comment]
I'll send out a PR to cover this shortly. I'm a busy bee right now... :D

**Comment by soundanalogous** [comment]
Fixed in https://github.com/firmata/arduino/pull/383
