### ISSUE TITLE
From one day to the next, Arduino doesn't work properly 

### ISSUE THREAD

**Issue by weezixx** [firmata/arduino#386]
Hi ! (English is not my mother tong, so I'm already sorry)

Short version:

I use an Arduino Mega, with Pyfirmata.

Yesterday I use this function : 

def moteur_capteur(moteur, capteur):
    board.digital[moteur].write(1)

    while True:
        if capteur.read() == False:
            board.digital[moteur].write(0)
            time.sleep(1)
            break

So it turn ON the motor, and when the sensor is touch (False), the motor stop.

Yesterday, it worked perfectly, and today … well not any more.

From yesterday to today I just added an other sensor … 

I check the connexion with the board and with the bread board, and every thing look fine to me. 

I even check the sensor with a code who tell me if its False or True, and it work perfectly !

Edit : I put on the top of the file : #usr/bin/python and it worked only once … 

I use the last version on Pyfirmata and PyCharm

Thanks for your help.

**Comment by soundanalogous** [comment]
Can you paste in your full script or link to it in a gist?

**Comment by weezixx** [comment]
Sorry I'm late !
I found a solution, without solving the problem ^^
I just create a copy of the file (with an other name), and when the problem occur I switch with the other file … And everything work perfectly.

Thanks again, and … see ya ;)

**Comment by naiveai** [comment]
Please close the issue, as it is solved.
