### ISSUE TITLE
Why we need to use nodejs

### ISSUE THREAD

**Issue by facetime88** [firmata/arduino#389]
I am trying to connect arduino board to client purely using javascript which every client can access it in ordinary browser, since I do not want to make another electron app and force user to use it just to make access to arduino happen.

I am not in deep understanding in how firmata protocol work via serial port. But if we can access usual USB webcam in browser with pure javascript, without need nodejs, then why do we need nodejs for firmata serial port? If we can communicate webcam with pure javascript, why not arduino?

**Comment by monteslu** [comment]
Firmata is a protocol.  It can work over many different types of transports.  This particular repository is for firmware implementation of firmata on arduino devices.  It's not a repository for firmata clients.  The clients can be written in any language.

Browsers have access to certain javascript APIs such as `getUserMedia` which can provide images from a webcam.   But they don't currently have a way to get to a regular serial port without a browser plugin.

That said, there is a bunch of progress going on for new APIs that can access hardware.

There's WebBluetooth, WebNFC, and WebUSB.  Older arduino devices such as the Arduino UNO aren't capable of being WebUSB devices.  However, other boards such as Arduino Leonardo and the newer ARM-based arduinos can work.  I've done some work on other transports implemented in javascript that might help you out:  https://github.com/monteslu?utf8=%E2%9C%93&tab=repositories&q=serial&type=&language=
