### ISSUE TITLE
Extended Configuration Proposal

### ISSUE THREAD

**Issue by soundanalogous** [firmata/arduino#39]
Copying this over from firmata.org.

**Extended Configuration Proposal**

for special configuration not covered in pinmode-specific messages

<pre>
/* set analogReference request
 * 0  START_SYSEX (0xF0)
 * 1  CONFIG_EXT command (0x7C)
 * 2  ANALOG_REF command (0x00)
 * 3  analog reference source (0-4, 0=DEFAULT, 1=INTERNAL, 2=INTERNAL1V1, 3=INTERNAL2V56, 4=EXTERNAL
 *    Values supported are device-specific. 
 *    See http://arduino.cc/en/Reference/AnalogReference and Arduino.h for details)
 */
</pre>

<pre>
/* set analogReadResolution request
 * 0  START_SYSEX (0xF0)
 * 1  CONFIG_EXT      command (0x7C)
 * 2  ANALOG_READ_RES command (0x01)
 * 3  analog read resolution (1-32, see http://arduino.cc/en/Reference/AnalogReadResolution for details)
 */
</pre>

<pre>
/* set analogWriteResolution request
 * 0  START_SYSEX (0xF0)
 * 1  CONFIG_EXT       command (0x7C)
 * 2  ANALOG_WRITE_RES command (0x02)
 * 3  analog write resolution (1-32, see http://arduino.cc/en/Reference/AnalogWriteResolution for details)
 */
</pre>

**Comment by shahanHasan** [comment]
How do i use them with python and pyfirmata to change analog reference to external and pass the reference voltage to analog read ? Any code snippets would be great.
