### ISSUE TITLE
Standard Firmata PWM Frequency

### ISSUE THREAD

**Issue by Ch3fk0ch88** [firmata/arduino#406]
Hello,
i hope someone can help me.
I controll my Mega 2560 with an Pi and NodeRed.
For that i have to use Standard Firmata at the Mega but i have to change the frequency to 25kHz to controll a fan.  I found a way to use 31.37255 kHz put i dont know how to create a 25kHz Signal.

Can Someone help me please?

Thanks

**Comment by Ch3fk0ch88** [comment]
Nobody  who did this?

**Comment by dtex** [comment]
Sorry for the slow response. Here’s a link to a Johnny-Five issue where we’ve discussed this. Regardless of wether you are using Johnny-Five, the issue is the same.

**Comment by Ch3fk0ch88** [comment]
Hi, thanks.
But u forgot to put in the Link ;)

**Comment by Ch3fk0ch88** [comment]
Can someone help me please?

**Comment by dtex** [comment]
Doh! Sorry 

https://github.com/rwaldron/johnny-five/issues/1469#issuecomment-395122350

**Comment by Ch3fk0ch88** [comment]
Hi,
i read it but not really find a solution who i can make it.

**Comment by dtex** [comment]
The article linked below is the important part. It may not be possible to get to 25 kHz. It depends on the pins' base clock speed. 

Just curious, what kind of motor/controller is it that requires this specific PWM frequency?

https://playground.arduino.cc/Code/PwmFrequency

**Comment by Ch3fk0ch88** [comment]
PC Fans run at 25kHz.

**Comment by dtex** [comment]
So this is a four wire motor with PWM on the 4th? If so, this thread may be what you need:

http://forum.arduino.cc/index.php?topic=18742

**Comment by Ch3fk0ch88** [comment]
SO i tested everthing i found but i dont get it work...

**Comment by dtex** [comment]
Can you share your modified firmata sketch?
