### ISSUE TITLE
Arduino MKR1010 support

### ISSUE THREAD

**Issue by eccoscreen** [firmata/arduino#407]
Hi will you guys be adding support for the MKR WiFi1010? I would try to edit Boards.h but Windows won't actually let me edit that file.

Thanks!

**Comment by soundanalogous** [comment]
This will enable a sketch to compile for this board, but I don't think it will enable WiFi support. For that you'd also have to edit [wifiConfig.h](https://github.com/firmata/arduino/blob/master/examples/StandardFirmataWiFi/wifiConfig.h)
