### ISSUE TITLE
15 arduinos, some randomly disconnects and JAVA uses 100% of CPU stoping the program

### ISSUE THREAD

**Issue by EloiVilalta** [firmata/arduino#411]
Hey there, first issue ever, 
I'm controlling 15 arduinos over Processing (last version 3.4) with a USB--> Ethernet -->USB conversors of up to 480Mb/s. 
At the start of the program I connect to all of them [0], the program sometimes reads/writes from one arduino or another (always with a 100ms delay between each "action" [1] as we discovered that the arduino doesn't disconects so easily [2]), but after some minutes no mather what, one or another arduino disconnects and it's impossible to continue, for example if there is a song playing, it breaks into small stops... Don't know what can I do as there is no example of how to use ethernet with processing and arduino yet, any idea?

Lets see if there is any guru over here that can help me, i'm pretty desesperate to run the program... 
If you need the program (almost 5000 lines on different pages) I can manage to share the dropbox link.

Many thanks to everyone! Let me know if you need anything.
(hope everyone understands my problem)

[0]: beeing able to disconnect when not in use and reconect when needed could be a great improvement to the use of this code .
[1]: input.read, output.write, key.released... 
[2]: using the firmata processing example "arduino_output", changing really fast the state makes the arduino disconnects and then there is an increase of CPU use, each arduino disconected adding a 30% usage on a i3-8100. So 3 arduinos disconected (of 15)=100% CPU = program unable to continue.

**Comment by soundanalogous** [comment]
It sounds like there is a problem on the Processing side, perhaps with using all those converters. There is only Serial connection support for Processing and there is no good reconnect support for Serial. If you were able to write a proper Ethernet client or server for Processing things will work much better. No one is maintaining the Firmata Processing library anymore so unfortunately you'd have to write the code yourself of find a contributor. If you're comfortable with JavaScript, [firmata.js](https://github.com/firmata/firmata.js) and [johnny-five.js](https://github.com/rwaldron/johnny-five) both support Ethernet (and WiFi) transports for Firmata. You can find examples [here](https://github.com/soundanalogous/firmata-client-examples/tree/master/firmata-js/network) and [here](https://github.com/soundanalogous/firmata-client-examples/tree/master/johnny-five/network).

**Comment by EloiVilalta** [comment]
Many thanks, going to try this ASAP, I guess by creating client1, client2, etc I can connect multiple arduinos right? Those examples only have one connected.
Again, many thanks

**Comment by soundanalogous** [comment]
However that firmata.js example I just provide isn't going to handle disconnected nodes gracefully. The johnny-five.js library has a way of connecting to multiple boards via Serial (USB) so you could also try that with your original setup. Here is an example: http://johnny-five.io/examples/board-multi/. But again, there is no good way to gracefully recover from dropped connections when using StandardFirmata, you'd really need custom Firmware on the board.

**Comment by EloiVilalta** [comment]
Dears, i'm trying to make a C++ program for it and then make a library for processing, will keep you up to date. Gonna try with websockets with that custom Firmware on the board.
Regards
