### ISSUE TITLE
Add Node-Red.org link to Readme.md too

### ISSUE THREAD

**Issue by PizzaProgram** [firmata/arduino#445]
I have spent 100+ hours before I've realized:
 - Firmata can be used with Node-Red too !

Please add a link to Readme.md client list:
https://nodered.org/docs/faq/interacting-with-arduino#firmata

**Comment by soundanalogous** [comment]
Please submit a pull request.

**Comment by PizzaProgram** [comment]
I can not do such thing. 
(That's why I've opened this ticket. Just wanted to help, so others do not have to search so much as I did...)

**Comment by PizzaProgram** [comment]
Sorry, never did anything like that before.
The "create pull request" button is disabled!
Tried to find out why > spent 15 minutes... sorry, no more time. Just wanted to help others...
If you can not do it either, forget about it.

**Comment by soundanalogous** [comment]
Done

**Comment by PizzaProgram** [comment]
Thanks :)
