### ISSUE TITLE
If I uploaded the program once, I need to press the reset button to upload the program again

### ISSUE THREAD

**Issue by xiebin2014** [firmata/arduino#467]
If I uploaded the program once, I need to press the reset button to upload the program again.
Is there any way to solve this problem

**Comment by soundanalogous** [comment]
Which board are you using?

**Comment by xiebin2014** [comment]
Thank you for your reply
Arduino Nano
ATmega328p(Old Bootloader)
StandardFirmata.ino

I think this is a common problem

**Comment by soundanalogous** [comment]
Do you have this problem with other Arduino sketches or just with Firmata?

**Comment by xiebin2014** [comment]
![image](https://user-images.githubusercontent.com/6446527/91939501-87bce600-ed28-11ea-89cb-637170b69fad.png)
EchoString is ok

**Comment by soundanalogous** [comment]
The Nano (at least since v3) has the auto reset functionality so this should not be an issue. StandardFirmata also fits on an ATmega328p so it's likely not a memory issue.

**Comment by xiebin2014** [comment]
You are right
There's something wrong with my board
