### ISSUE TITLE
To drive a Servo what Capabilities do i need from a board?

### ISSUE THREAD

**Issue by ale-novo** [firmata/arduino#500]
Hi, i wish to drive a Servo with Firmata, however im confused what capabilities should the board have to support this.
Im writing a script to detect the board capabilities and determine if that board can or cant drive a servo.

at the moment im checking for both PWM and SERVO capability
PWM                (0x03)
SERVO              (0x04)

is this correct? or should i only check for SERVO capability?
thanks.

**Comment by zfields** [comment]
It's been a while since I've dug in, but I believe `SERVO` works as a specialized super set of `PWM` and will be enough on it's own.

**Comment by ale-novo** [comment]
thanks!
