### ISSUE TITLE
software serial (and support for additional UARTs)

### ISSUE THREAD

**Issue by soundanalogous** [firmata/arduino#97]
A number of requests have been made to add software serial support to Firmata. I think instead of just software serial, it would be better to support both software serial and [additional UARTs](http://arduino.cc/en/reference/serial) (on a Mega for example: Serial1, Serial2, etc).

For those who are asking for serial support in Firmata, what are your use cases?
- read only serial devices?
- read/write serial devices
- board to board communication over serial?
- anything else?

I need to know this in order to determine how much of the Stream interface to expose. In the simplest example I assume a read buffer and a write buffer would be sufficient - simply echoing the serial data. However are there also use cases that would need the `peek()` or `flush()` methods. There are also limitations in buffer sizes (64 bytes incoming... but you have to split every byte so you only get 32 bytes... even less actually after stripping out the command bytes so more like 29 or 30 bytes of actual data).

Software serial also interferes with some timer-based features. So PWM may not work as expected when using Software serial. There are other potential collisions as well. However this can be avoided by using a Leonardo, Mega or other board that has separate hardware serial ports (Serial1, Serial2, etc). It would use the same protocol as SW serial with the main difference being that you'd configure with a port number rather than a pair of pin numbers.

**Comment by Draghtnod** [comment]
Hi, I merged the head of @soundanalogous SoftwareSerial branch with the Configurable branch and added it to the reporting feature. I want to read the Data of a GY-GPS6MV2 on an ODroid U3 IO-Shield (ATMega328P@16MHz). Everything works like a charm except for one thing:

I had to adjust the timing values in SoftwareSerial.cpp to get stable data, but there are incorrect bits in the middle of the transmissions. Only some characters/bit-pattern are affected every ~15 bytes. The locations of these errors are stable, even if i modify the timing values. So it theoretically shouldn't be a timing issue. The GPS works fine (checked with external UART) and the signal on the input pin is also clear (checked with oscilloscope). It is also no performance issue (removed all components of the Firmata except for SoftSerial and got the exact same error). The reporting frequency has no influence. Increasing the receive-buffer also didn't help.

Could that be an issue with the Firmata part of the SoftSerial?

**Comment by soundanalogous** [comment]
I never finished the work in the SoftwareSerial branch so it's likely the issue is in the Firmata code.

**Comment by Draghtnod** [comment]
Ok I'll start searching in the SoftwareSerial code and send you a pull request if i find something.

**Comment by 9600** [comment]
Hi @Draghtnod, thanks for letting me know!!1!

**Comment by soundanalogous** [comment]
Just know that I'm planning to change the implementation to also accommodate hardware serial (for boards that have multiple uarts). I may have time this weekend to work on it. I've also posted the most recent Firmata Serial protocol proposal here: https://github.com/firmata/protocol/blob/serial/serial-proposal.md

**Comment by Draghtnod** [comment]
Your proposal looks good. I got three things to mention:
1) What about multiple software serials? The library supports this by switching the RX port with listen().
2) The software serial buffer is only 64 byte. Even with 9600 baud you would have to read every ~50ms to not miss any data. So adding a reporting feature would be nice to avoid hammering frequent RX requests.
3) The RX and TX pins are interchanged at new SoftwareSerial(txPin, rxPin). That was quite confusing. :) http://arduino.cc/en/Reference/SoftwareSerialConstructor

**Comment by Draghtnod** [comment]
I solved my bug. It must be somewhere in the HardwareSerial module of Arduino 1.0.1(+dfsg-7 debian arduino-core package). After upgrading to Arduino 1.6.1 everything works fine out of the box.

**Comment by soundanalogous** [comment]
Good to know it works as is. I had never actually tested the code with an actually serial device, only compiled it with no errors then got busy with other projects.

**Comment by soundanalogous** [comment]
I plan to change the draft protocol to include both a READ_ONCE and a READ_CONTINUOUS (reporting) mode. READ_CONTINUOUS would dump the serial buffer at the sampling interval (19ms by default). It would be the user's responsibility to ensure data is assembled correctly. Firmata will blindly relay the serial data to the client.

I would be possible to optionally specify a terminal char that could dump the buffer when that char is received (as in [@kraman's implementation](https://github.com/kraman/go-firmata/commit/e7742e31a69a2e1f9731db22d5cc27b5c994d0a3#diff-a07db380352626960ae6330f05c0efd6R722)). This may be helpful for some serial devices.

**Comment by rwaldron** [comment]
This sounds good to me, looking forward to testing :)

**Comment by damellis** [comment]
Some comments on the pull request: https://github.com/firmata/protocol/pull/28/files 

SERIAL_READ goes from the Firmata client to the board, right?

The sizes of any buffers (whether send or receive) seem like they should be specified in the firmware and communicated to the Firmata client in a capability message of some sort, rather than specified by the client.

It seems like the protocol should support more than one software serial port. Also, there should probably be a way for the client to discover the number and (pin) locations of the hardware serial ports.

For sending serial data to the client, do you really need a way to do read once? Or to buffer until a particular character arrives? It seems like you could get away with just the start reading and stop reading commands, with the firmware sending available bytes while reading is enabled.

One concern might be with the jitter introduced by sending a variable number of serial data bytes each time through the loop. Maybe the host client can specify the number of bytes it wants to get on each message / loop (maybe with an "all" option)? (Then you could balance between getting the bytes quickly and slowing down everything else.)

**Comment by soundanalogous** [comment]
> SERIAL_READ goes from the Firmata client to the board, right?

Correct

> It seems like the protocol should support more than one software serial port.

Supporting multiple software serial ports is tricky since I need to dynamically create them rather than declare them all up front. I could declare a certain number up front regardless if the actually intends to user SoftSerial. I'd have to see how much memory this would consume and at which point I rule out lower ram devices.

> Also, there should probably be a way for the client to discover the number and (pin) locations of the hardware serial ports.

I was thinking the configuration query would handle this. There would be a single `SERIAL` pin type. For the first SoftSerial TX pin, the configuration query will return `pin mode: SERIAL`, `pin resolution: STX0`.

> For sending serial data to the client, do you really need a way to do read once? Or to buffer until a particular character arrives?

I agree with you here and will remove READ_ONCE for the first version. I'll keep the separate byte for specifying READ_MODE since that will enable me to add READ_ONCE in the future if it turns out to be useful.

> One concern might be with the jitter introduced by sending a variable number of serial data bytes each time through the loop.

This is why I was debating relaying the serial data on each iteration of loop or at the sampling interval. If I use the sampling interval I'll need a much larger buffer in case the user is interfacing with a 56k or 115k peripheral. The advantage of sending once per loop is I can probably avoid a separate buffer, thus saving memory and keeping the feature compatible with ATmega328 boards. Your idea of enabling the user to set a number of bytes to be sent per iteration is interesting as well. It would probably have to be a specific range of values in order to avoid overflowing the serial buffer (assuming the existing 64k serial buffer, but more flexible with a separate larger buffer).

**Comment by damellis** [comment]
Yeah, I was assuming that the host couldn't request more bytes per loop than the client can buffer. You might want a way for the host to discover how big the client buffers are (for both sending and receiving). Either way, though, the client can always just send fewer actual bytes than the host has requested (since this is what would happen if fewer bytes were available). I guess you'd need to pad out the message with empty / default values to ensure a consistent message length. 

Does a sampling interval help? It might make the jitter / lag less frequent but it will still happen (and probably be longer when it does). 

As for multiple software serial ports, it might be good to keep them as an option in the protocol (e.g. have a bit for SW vs. HW) even if the initial implementation only has one.

**Comment by soundanalogous** [comment]
The way I have currently crafted the protocol, you can use multiple hardware ports and a mix of a single sw serial port and one or more hw serial ports. In order to use multiple software serial ports I need to add another message (SWITCH_SW_SERIAL_PORT) to switch software serial ports (in the Arduino implementation this would call the `listen()` method).

**Comment by soundanalogous** [comment]
I have opened a pull request for an implementation of a Firmata Serial protocol that supports both Hardware and Software serial. Please test it against some serial devices and provide any feedback on the implementation: https://github.com/firmata/arduino/pull/205.

**Comment by soundanalogous** [comment]
Added in Firmata 2.5. See [StandardFirmataPlus](https://github.com/firmata/arduino/blob/master/examples/StandardFirmataPlus/StandardFirmataPlus.ino) for the implementation and also the protocol here: https://github.com/firmata/protocol/blob/master/serial.md

**Comment by Davis4Create** [comment]
Hi Jeff,
These days I am trying to make my Arduino UNO board get some responses from a voice recognition module, which is ASR-M08-A, and I would also like to make the board communicate with a software called Snap4Arduino (S4A) on PC after uploading the StandardFirmata. Now the problem is: only one hardware serial port provided on the board, but I should use two serial ports simultaneously. I think what you have done here would help me a lot to solve the problem. But there are still some problems, cause I need to make some new blocks in S4A to mirror the new functions created in the firmware, so I need to check whether the StandardFirmataPlus you implemented is compatible with S4A or not, and can you please show me some base knowledge of firmata to custom the firmware, as my work would be much related to this in the near future. 
Thank you very much!
Kind regards,
Davis

**Comment by soundanalogous** [comment]
You would need to implement the [Firmata serial interface](https://github.com/firmata/protocol/blob/master/serial.md) in the Snap4Arduino source code (or request the Snap4Arduino) team to add it.

You should not need to make any changes to the firmware itself. All of the changes need to be made to Snap4Arduino to add support for Firmata serial.

Also you can use both hardware and software serial so you could still use an Arduino Uno, however you will see better performance if you use a board that has an extra UART such as an Arduino Leonardo or even better an Arduino Zero.

**Comment by Davis4Create** [comment]
@soundanalogous All right, I think I have got some ideas to fix the problem, thanks for your help.

**Comment by q2dg** [comment]
My use case would be controlling via Bluetooth (a.k.a software serial) an Arduino Uno from an Android phone using Processing

However, I see in StandardFirmataPlus source code that "At the time of this writing, StandardFirmataPlus will still compile and run  on ATMega328p and ATMega32u4-based boards, but future versions of this sketch  may not as new features are added" so I infer using this script in my setup may not work (am I wrong?)

My question is, then: how could strip hardwareserial part from Firmata (which I don't want) to keep only the softwareserial part so it fits better on my Arduino UNO? I've thought using http://firmatabuilder.com but I miss a "Bluetooth" option to "Connection type" combobox . Would it be difficult to add this option?

Thanks!!!

**Comment by soundanalogous** [comment]
@q2dg I need to better understand what you are trying to accomplish. Are you hoping to interact with an Uno via Firmata from a Processing application running on an Android phone? And by this method you want to use BT as the transport for Firmata?

**Comment by q2dg** [comment]
@soundanalogous YES!

**Comment by soundanalogous** [comment]
What type of BT radio are you connecting to the Arduino UNO?

**Comment by q2dg** [comment]
A HC-06 module

**Comment by soundanalogous** [comment]
Ok, you don't need SoftwareSerial. You actually need to attach the HC-05/06 to pins 0 and 1 on the Uno (HardwareSerial) and just use StandardFirmata. You'll also need to change the baud rate in StandardFirmata to 9600 since I think the HC-06 at least only supports that rate. The problem with the HC-0X modules is they don't offer a way to wire up reset so you'll need to manually reset the Arduino before starting the Processing sketch. What you really need for something like this is the [Adafruit Bluefruit easy link](https://www.adafruit.com/products/1588), it will use 57600 board and also respect the reset signals.

On the Android side, you'll need a Firmata client with BT support. The processing Firmata client doesn't have this. It only works over Serial currently.

Another option is to use an Arduino 101, which has built in Bluetooth LE. This works with Firmata (see StandardFirmataBLE). However there is no support for Processing yet (at least not that I know of). It would work with Android's BLE stack, but there is no Firmata version for Android that uses the BLE stack yet, they all still appear to use Serial. It's something I plan to work on if I ever find the time unless someone beats me to it.

**Comment by q2dg** [comment]
Ok, thanks a lot for your long and so clear explanation. Internet is a better place with people like you.
Thanks!!
